# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


bioc_packages:
  - zlibbioc
  - Rhtslib



# NOTES:
# Not doing devel on osx because CRAN doesn’t publish OSX binary packages for r-devel.
# Including `r_binary_packages` in oldrel caused "number of columns of matrices must
#     match" error



matrix:
  include:
  - r: devel
    os: linux
    cache: packages
  - r: release
    os: linux
    cache: packages
    env:
      - PKG_TARBALL=jackalope_1.1.1.tar.gz
    r_packages:
      - covr
      - pkgdown
    after_success:
      - Rscript -e 'library(covr); codecov()'
      - tar -C .. -xf $PKG_TARBALL
      - rm -rf jackalope.Rcheck
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docs
        on:
          branch: master
  - r: release
    os: osx
    cache: packages
    r_binary_packages:
      - Rcpp
      - RcppArmadillo
      - RcppProgress
      - ape
      - R6
      - knitr
      - testthat
  - r: oldrel
    os: linux
  - r: oldrel
    os: osx


# safe list
branches:
  only:
  - master
  - develop

## To deal with some packages trying to use OpenMP on macOS,
## and to deal with "File `inconsolata.sty' not found." error
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
    mkdir -p ~/.R;
    echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars;
    echo "SHLIB_OPENMP_CFLAGS = " >>~/.R/Makevars;
    brew cask install basictex;
    sudo tlmgr update --self;
    sudo tlmgr update --all;
    sudo tlmgr install titling framed inconsolata;
    sudo tlmgr install collection-fontsrecommended;
    fi
