# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false


bioc_packages:
  - zlibbioc
  - Rhtslib

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - ape
  - R6
  - knitr
  - testthat


# NOTES:
# Not doing devel on osx because CRAN doesn’t publish OSX binary packages for r-devel.
# Using `osx_image: xcode9.2` to use macOS version 10.12
# Caching packages in linux->oldrel causes problems


matrix:
  include:
  - r: release
    os: linux
    cache: packages
    r_packages:
      - covr
    after_success:
      - Rscript -e 'library(covr); codecov()'
  - r: devel
    os: linux
    cache: packages
  - r: oldrel
    os: linux
  - r: release
    os: osx
    osx_image: xcode8.3
    cache: packages
  - r: oldrel
    os: osx
    osx_image: xcode8.3


# safe list
branches:
  only:
  - master
  - develop

## To deal with some packages trying to use OpenMP on macOS:
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
    mkdir -p ~/.R;
    echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars;
    echo "SHLIB_OPENMP_CFLAGS = " >>~/.R/Makevars;
    fi

